### ISSUE TITLE
Help installing it for an english speaker please:)?

### ISSUE THREAD

**Issue by APISeeker** [jiangyuxiaoxiao/Bert-VITS2-UI#11]
Hello,
I am not sure what to do to install it?
There is the "release" file, then what should I click when I Unzipp the archive? There is a .sh file but I am on WINDOWS. 
Any help is appreciated?

I can also do git clone ...
then..?

Thanks.
Any information can be useful.

**Comment by jiangyuxiaoxiao** [comment]
This is just the inference interface of bert-vits2. You only need to run `hiyori.py`, but the prerequisite is that you have a trained model.

**Comment by jiangyuxiaoxiao** [comment]
> This is just the inference interface of bert-vits2. You only need to run `hiyori.py`, but the prerequisite is that you have a trained model.

You may also need to configure the running of hiyori.py in the config.yml file. The config.yml file already contains detailed instructions. You can use machine translation tools like Google Translate, or large language models such as ChatGPT, for translation.

**Comment by jiangyuxiaoxiao** [comment]
Training is not part of this project, it pertains to Bert-Vits2. Since Bert-Vits2 lacks a detailed readme explanation, and most tutorials are in [Chinese](https://b23.tv/yuAB25Q) and [Japanese](https://zenn.dev/litagin/articles/b1ddc1da5ea2b3), it can be challenging for English speakers. Maybe you can use Google Translate.

**Comment by APISeeker** [comment]
Ok thank you very much, I can train models with rvc and get .pth files, right?
